param(
  [string]$ProjectRoot = "D:\lyh\agent\agent-frame\ShopOps",
  [string]$TaskPackId = "shopops-goal-2026-06-03",
  [string[]]$TaskIds = @("T01","T02","T03","T04","T05","T06","T07","T08","T09","T10","T11","T12","T13"),
  [switch]$Force,
  [switch]$DryRun,
  [int]$MaxRepairAttempts = 1
)

$ErrorActionPreference = "Stop"
Set-Location -LiteralPath $ProjectRoot

$taskFiles = [ordered]@{
  T01 = "docs/auto-execute/shopops-goal-tasks/T01-source-intake-and-current-implementation-audit.md"
  T02 = "docs/auto-execute/shopops-goal-tasks/T02-requirements-traceability-refresh.md"
  T03 = "docs/auto-execute/shopops-goal-tasks/T03-feishu-bitable-storage-real-and-local-proof.md"
  T04 = "docs/auto-execute/shopops-goal-tasks/T04-qianniu-order-center-live-crawler.md"
  T05 = "docs/auto-execute/shopops-goal-tasks/T05-taobao-api-boundary-and-nonblocking-config.md"
  T06 = "docs/auto-execute/shopops-goal-tasks/T06-qianniu-promotion-center-cost-crawler.md"
  T07 = "docs/auto-execute/shopops-goal-tasks/T07-metric-snapshot-delta-engine-refresh.md"
  T08 = "docs/auto-execute/shopops-goal-tasks/T08-no-zero-failure-and-data-status-regression.md"
  T09 = "docs/auto-execute/shopops-goal-tasks/T09-alerts-task-log-and-scheduler-isolation.md"
  T10 = "docs/auto-execute/shopops-goal-tasks/T10-daily-report-and-operator-runbook.md"
  T11 = "docs/auto-execute/shopops-goal-tasks/T11-full-local-test-suite-and-acceptance-scripts.md"
  T12 = "docs/auto-execute/shopops-goal-tasks/T12-report-integrity-secret-guard-code-review.md"
  T13 = "docs/auto-execute/shopops-goal-tasks/T13-final-acceptance-gate-fail-closed.md"
}

$acceptable = @(
  "PASS",
  "PASS_WITH_LIMITATION",
  "PASS_NEEDS_MANUAL_UI_REVIEW",
  "BLOCKED_BY_ENVIRONMENT",
  "BLOCKED_BY_MISSING_SOURCE",
  "DOCUMENTED_BLOCKER"
)
$repairStatuses = @("REPAIR_REQUIRED", "HARD_FAIL", "FAIL", "IN_SCOPE_GAP", "INVALID_JSON", "STALE_RESULT")
$logDir = Join-Path $ProjectRoot "docs/auto-execute/logs/T00"
New-Item -ItemType Directory -Force -Path $logDir | Out-Null

function Get-TaskStatus {
  param([string]$TaskId)

  $resultPath = Join-Path $ProjectRoot "docs/auto-execute/results/$TaskId.json"
  $handoffPath = Join-Path $ProjectRoot "docs/auto-execute/latest/$TaskId-HANDOFF.md"
  $exists = (Test-Path -LiteralPath $resultPath) -and (Test-Path -LiteralPath $handoffPath)
  if (-not $exists) {
    return [pscustomobject]@{
      task = $TaskId
      exists = $false
      current = $false
      status = "MISSING_ARTIFACT"
      taskPackId = $null
      resultPath = $resultPath
      handoffPath = $handoffPath
      reason = "result JSON or HANDOFF is missing"
    }
  }

  try {
    $json = Get-Content -Raw -Encoding UTF8 -LiteralPath $resultPath | ConvertFrom-Json
  } catch {
    return [pscustomobject]@{
      task = $TaskId
      exists = $true
      current = $false
      status = "INVALID_JSON"
      taskPackId = $null
      resultPath = $resultPath
      handoffPath = $handoffPath
      reason = $_.Exception.Message
    }
  }

  $actualPack = [string]$json.task_pack_id
  $status = [string]$json.status
  $isCurrent = $actualPack -eq $TaskPackId
  $effectiveStatus = if ($isCurrent) { $status } else { "STALE_RESULT" }
  $reason = if ($isCurrent) { "current task_pack_id" } else { "missing or mismatched task_pack_id '$actualPack'" }
  return [pscustomobject]@{
    task = $TaskId
    exists = $true
    current = $isCurrent
    status = $effectiveStatus
    rawStatus = $status
    taskPackId = $actualPack
    resultPath = $resultPath
    handoffPath = $handoffPath
    reason = $reason
  }
}

function Write-RepairQueue {
  param([object[]]$Rows)

  $path = Join-Path $ProjectRoot "docs/auto-execute/repair-queue.md"
  $lines = @(
    "# ShopOps Goal Repair Queue",
    "",
    "Generated by T00 relay status check for task_pack_id $TaskPackId.",
    "",
    "| Task | Status | Reason | Result | HANDOFF |",
    "| --- | --- | --- | --- | --- |"
  )
  foreach ($row in $Rows) {
    if (($repairStatuses -contains $row.status) -or $row.status -eq "MISSING_ARTIFACT") {
      $resultPath = [string]$row.resultPath
      $handoffPath = [string]$row.handoffPath
      $lines += "| $($row.task) | $($row.status) | $($row.reason) | ``$resultPath`` | ``$handoffPath`` |"
    }
  }
  if ($lines.Count -eq 6) {
    $lines += "| none | PASS | no repair queue entries | | |"
  }
  $lines | Out-File -FilePath $path -Encoding utf8
  return $path
}

function Invoke-FreshCodexTask {
  param([string]$TaskId, [int]$Attempt, [string]$Reason)

  $relativeTaskPath = $taskFiles[$TaskId]
  if (-not $relativeTaskPath) { throw "Unknown task id: $TaskId" }
  $taskPath = Join-Path $ProjectRoot $relativeTaskPath
  if (-not (Test-Path -LiteralPath $taskPath)) { throw "Missing task file: $taskPath" }

  $taskLogDir = Join-Path $ProjectRoot "docs/auto-execute/logs/$TaskId"
  New-Item -ItemType Directory -Force -Path $taskLogDir | Out-Null
  $stamp = Get-Date -Format "yyyyMMdd-HHmmss"
  $eventLog = Join-Path $taskLogDir "codex-exec-$stamp-attempt-$Attempt.jsonl"
  $lastMessage = Join-Path $taskLogDir "last-message-$stamp-attempt-$Attempt.txt"

  $prompt = @"
Use auto-execute. Execute only $taskPath. Treat this as one fresh task boundary for task_pack_id $TaskPackId.
Read AGENTS.md, the total task pack, T00, and required inputs named by the task.
Do not execute any other Txx task. Implement/test/repair within this task scope.
Write docs/auto-execute/results/$TaskId.json and docs/auto-execute/latest/$TaskId-HANDOFF.md.
If blocked, classify in durable files and route repair; do not end with only chat text.
Relay reason: $Reason
"@

  if ($DryRun) {
    return [pscustomobject]@{
      task = $TaskId
      action = "dry-run"
      attempt = $Attempt
      reason = $Reason
      taskPath = $taskPath
      eventLog = $eventLog
      lastMessage = $lastMessage
    }
  }

  & codex exec -C $ProjectRoot --sandbox workspace-write --output-last-message $lastMessage --json $prompt 2>&1 |
    Out-File -FilePath $eventLog -Encoding utf8
  return [pscustomobject]@{
    task = $TaskId
    action = "run"
    attempt = $Attempt
    reason = $Reason
    exitCode = $LASTEXITCODE
    eventLog = $eventLog
    lastMessage = $lastMessage
  }
}

$probeRows = @()
foreach ($taskId in $TaskIds) {
  if (-not $taskFiles.Contains($taskId)) { throw "Unknown task id: $taskId" }
  $probeRows += Get-TaskStatus -TaskId $taskId
}

$repairQueuePath = Write-RepairQueue -Rows $probeRows
$firstOpen = $probeRows | Where-Object {
  $Force -or
  (-not $_.current) -or
  ($_.status -eq "MISSING_ARTIFACT") -or
  ($repairStatuses -contains $_.status) -or
  (-not ($acceptable -contains $_.status))
} | Select-Object -First 1

$actions = @()
if ($firstOpen) {
  $actions += Invoke-FreshCodexTask -TaskId $firstOpen.task -Attempt 1 -Reason $firstOpen.reason
}

$summary = [pscustomobject]@{
  task_pack_id = $TaskPackId
  mode = if ($DryRun) { "dry-run" } else { "execute" }
  timestamp = (Get-Date).ToString("o")
  project_root = $ProjectRoot
  checked_tasks = $probeRows
  selected_next_task = if ($firstOpen) { $firstOpen.task } else { $null }
  actions = $actions
  repair_queue = $repairQueuePath
  stop_condition = if ($firstOpen) { "one task selected; rerun after artifact validation" } else { "all tasks current and acceptable" }
}

$summaryPath = Join-Path $logDir ("orchestrator-" + (Get-Date -Format "yyyyMMdd-HHmmss") + ".json")
$summary | ConvertTo-Json -Depth 10 | Out-File -FilePath $summaryPath -Encoding utf8
$summary
